version: '2'

volumes:
    vendor:
    var:
    cd_ps_sandbox_1765.sql.gz:

services:
    mysql:
        image: mysql:5
        ports:
            - "3306:3306"
        volumes:
            - ./cd_ps_sandbox_1765.sql.gz:/docker-entrypoint-initdb.d/cd_ps_sandbox_1765.sql.gz:ro
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: prestashop
        restart: always
    apache:
        container_name: prestashop
        image: prestashop/base:7.2-apache
        environment:
            PS_INSTALL_AUTO: 0
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html/:delegated
        restart: always

