# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DB_NAME: ps_sandbox_1765

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    services:
      mysql:  
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{DB_NAME}}
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
      httpd:  
        image: httpd:2.4
        ports:
          - 8080:80
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'

    - name: composer install
      run: composer install --no-interaction --no-progress --no-scripts -o --ansi
      
    - name: Phplint
      run: ./vendor/bin/phplint ./classes
