# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DB_NAME: ps_sandbox_1765

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{env.DB_NAME}}
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        volumes:  
          - ${{ github.workspace }}/cd_ps_sandbox_1765.sql.gz:/docker-entrypoint-initdb.d/cd_ps_sandbox_1765.sql.gz:ro
      prestashop/base:
        image: prestashop/base:7.2-apache
        ports:
          - 8080:80
        volumes:
            - ${{ github.workspace }}:/var/www/html/:delegated
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        extensions: php-pecl-zip

    - name: composer install
      run: composer install --no-interaction --no-progress --no-scripts -o --ansi

    - name: Phplint
      run: ./vendor/bin/phplint ./classes

    - name: Replace config
      run: envsubst < ./app/config/parameters.php.dist > ./app/config/parameters.php

    - name: Database migration fixture
      run: mysql -h 127.0.0.1 ${{env.DB_NAME}} < "update ps_shop_url set physical_uri = '/'";
    
    #- uses: mysql
    #  with:
    #    sql: update ps_shop_url set physical_uri = '/'
    
    - name: request homepage
      run: curl -v -L http://localhost
